# Generated by Django 5.2.6 on 2025-09-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
