# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='main_job_detaile_12dc2f_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='detailer',
            new_name='primary_detailer',
        ),
        migrations.AddField(
            model_name='job',
            name='detailers',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='main.detailer'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['primary_detailer', 'status', 'appointment_date', 'appointment_time', 'booking_reference'], name='main_job_primary_12dc2f_idx'),
        ),
    ]
