# Generated by Django 5.2.6 on 2025-09-08 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='PayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bankaccount')),
                ('detailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_history', to='main.detailer')),
                ('earnings', models.ManyToManyField(related_name='payouts', to='main.earning')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['detailer', 'status', 'initiated_at'], name='main_payout_detaile_cbbe27_idx'), models.Index(fields=['payout_reference'], name='main_payout_payout__d9a088_idx')],
            },
        ),
    ]
