# Generated by Django 5.2.6 on 2025-09-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_earning_payment_status_payouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='payment_type',
            field=models.CharField(choices=[('request', 'Request'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20),
        ),
    ]
