# Generated by Django 5.2.7 on 2025-11-05 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_allow_push_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('image', models.ImageField(upload_to='jobs/images/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.job')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
                'indexes': [models.Index(fields=['job', 'image_type'], name='main_jobima_job_id_84252a_idx'), models.Index(fields=['uploaded_at'], name='main_jobima_uploade_ae4ea3_idx')],
            },
        ),
    ]
