# Generated by Django 5.2.11 on 2026-02-04 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job_primary_detailer_and_detailers'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_state', models.CharField(choices=[('traveling', 'Traveling/Driving'), ('waiting', 'Waiting'), ('active', 'Active Cleaning')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_earned', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.RenameField(
            model_name='earning',
            old_name='commission',
            new_name='hourly_earnings',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='main_job_primary_13f40f_idx',
            old_name='main_job_primary_12dc2f_idx',
        ),
        migrations.RemoveField(
            model_name='detailer',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='earning',
            name='hourly_rate_active',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='earning',
            name='hourly_rate_inactive',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='earning',
            name='total_active_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='earning',
            name='total_inactive_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='primary_detailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_jobs', to='main.detailer'),
        ),
        migrations.AddField(
            model_name='jobactivitylog',
            name='detailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.detailer'),
        ),
        migrations.AddField(
            model_name='jobactivitylog',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='main.job'),
        ),
        migrations.AddIndex(
            model_name='jobactivitylog',
            index=models.Index(fields=['job', 'detailer', 'is_active'], name='main_jobact_job_id_fcf13d_idx'),
        ),
    ]
