# Generated by Django 5.2.7 on 2025-11-07 01:27

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_jobimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='after_photo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='before_photo',
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(upload_to=main.models.job_image_upload_path),
        ),
    ]
