# Generated by Django 5.2.6 on 2025-09-12 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_payouthistory_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='main.job'),
        ),
    ]
