# Generated by Django 5.2.6 on 2025-09-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_rescheduled', 'Booking Rescheduled'), ('cleaning_completed', 'Cleaning Completed'), ('appointment_started', 'Appointment Started'), ('booking_created', 'Booking Created'), ('pending', 'Pending')], default='pending', max_length=255),
        ),
    ]
