# Generated by Django 5.2.6 on 2025-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_notification_token_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_push_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
