# Generated by Django 5.2.6 on 2025-09-15 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_allow_email_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='main.job'),
            preserve_default=False,
        ),
    ]
