# Generated by Django 5.2.6 on 2025-09-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_job_loyalty_benefits_job_loyalty_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
