# Generated by Django 5.2.6 on 2025-09-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_job_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_rescheduled', 'Booking Rescheduled'), ('booking_created', 'Booking Created'), ('cleaning_completed', 'Cleaning Completed'), ('appointment_started', 'Appointment Started'), ('review_received', 'Review Received'), ('pending', 'Pending'), ('car_ready', 'Car Ready'), ('payment_received', 'Payment Received'), ('reminder', 'Reminder'), ('system', 'System')], default='pending', max_length=255),
        ),
    ]
